DPE-1511 Do not expect a hardcoded database name for the legacy mysql relation
canonical/mysql-test-app pull request #8
Opened 2023-06-01 20:12 UTC by shayancanonical

2023-06-01 21:06 UTC, paulomach approved these changes

2023-06-05 10:10 UTC, taurus-forever requested changes

2023-06-05 10:10 UTC, taurus-forever commented on src/relations/legacy_mysql.py
>          database_name = relation_data["database"]
Agree to Carl, use in line 63:
> self.charm.app_peer_data[f"{LEGACY_MYSQL_RELATION}-database"] = relation_data["database"]

2023-06-30 11:43 UTC, taurus-forever approved these changes

2023-07-03 10:28 UTC, delgod approved these changes

2023-09-25 10:40 UTC, shayancanonical commented
Closing as this PR is very stale and no longer necessary

2023-09-25 10:40 UTC, closed without merging